### ISSUE TITLE
modules example

### ISSUE THREAD

**Issue by matheus7mm** [Baseline11/resident#18]
@matejthetree please if possible create 2 modules where the 1st is a screen where we have 1 input and 1 button, then we collect a value from the input (for instance First Name), then hitting the button we go to a 2nd module where we have another screen with an input and another button. Hitting the button in the 2nd screen we should be able to collect this second value (for instance Last Name) and trigger a function somewhere where we have these 2 values. I think having this example would be a great way to understand how you would manage the states, modules, and these use cases.

**Comment by matejthetree** [comment]
Consider a module nothing more than a widget, cause in flutter everything is a widget :D

now, you have login flow module, and if you need to pass some data to home screen, you can save that data inside the store on root level.

one app flow module is initialized, it can read dependencies from the parent.

you should be more thinking individually.

first module has data that needs to be used inside the app, it passes that data to parent before disposing.

the second module has requirement for data, you can initialize it in constructor, or take it from dependency of the parent.

there is never one module, that goes straight to the next module, somebody is always managing the modules from above, and if nobody, there is main.dart
